default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: backend_project_api_development
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: backend_project_api_test
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  <<: *default
  # username: postgres
  # password: <%= ENV['POSTGRES_PASSWORD'] %>